services:
  - type: web
    name: medical-bot
    env: docker
    dockerfilePath: ./Dockerfile
    envVars:
      - key: PINECONE_API_KEY
        sync: false
      - key: GEMINI_API_KEY
        sync: false
